---
title: "Device Type Prediction"
author: "Nada Hossam"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    keep_md: yes
  pdf_document: default
  word_document: default
---



# Executive Summary

The main goal is to 


# Loading the Data

The data is loaded from the files and NA values are removed and also near zero values are removed. The data which is not needed is neglected.

```{r}

library(caret)
library(randomForest)

trainData <- read.csv("E:/Nada/Others/Courses/Data Science Specialization/Ex/Course 8/pml-training.csv", sep = ",", na.strings = c("NA", ""))

testData <- read.csv("E:/Nada/Others/Courses/Data Science Specialization/Ex/Course 8/pml-testing.csv", sep = ",", na.strings = c("NA", ""))

trainData[1:5] <- NULL
testData[1:5] <- NULL
dim(trainData)

na_cols <- colSums(is.na(trainData)) > nrow(trainData) * 0.7
trainData <- trainData[!na_cols]
testData <- testData[!na_cols]

nsv <- nearZeroVar(trainData)
trainData <- trainData[-nsv]
testData <- testData[-nsv]

str(trainData)
table(trainData$classe)

```



# Building the Model


```{r}

in_train <- createDataPartition(y = trainData$classe, p = 0.7, list = FALSE)
trainDataX <- trainData[in_train, ]
trainDataY <- trainData[-in_train, ]

mdl <- randomForest(classe ~ ., data = trainDataX)
mdl

```



## Calculating Accuracy of Model


```{r}

validatPredict <- predict(mdl, trainDataY)
conf_matrix <- confusionMatrix(validatPredict, trainDataY$classe)
conf_table <- conf_matrix$table
validation_accuracy <- (sum(diag(conf_table))/sum(conf_table)) * 100
out_of_sample_error <- 100 - validation_accuracy
out_of_sample_error

```


# Testing the Model

```{r}

prediction <- predict(mdl, testData)
prediction

```

